version: 2
jobs:
  build-test:
    docker:
      - image: circleci/python:3.5.1
    working_directory: ~/
    steps:
      - run: sudo pip install -U $TF_BINARY_URL
      - run: sudo pip install Keras
      - run:
          name: 'python run_custom_env.py'
          command: python run_custom_env.py

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-test: