version: 2
jobs:
  build-test:
    docker:
      - image: circleci/python:3.5.1
	environment:
	  TF_BINARY_URL: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp35-cp35m-linux_x86_64.whl
	  KERAS_BACKEND: tensorflow
    working_directory: ~/
    steps:
      - run: sudo pip install -U $TF_BINARY_URL
      - run: sudo pip install Keras
      - run:
          name: 'python run_custom_env.py'
          command: python run_custom_env.py

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-test:
